### ISSUE TITLE
你好，大佬，我很喜欢你这个header。请问你这项目是要自己起一个minio后台才能实现把。如果可以静态实现，可不可以出一个文档放在项目里。谢谢喵

### ISSUE THREAD

**Issue by TwinZagreus** [Zhousiru/Zhousiru#1]

**Comment by zhousiru** [comment]
这个 Header 其实就是一个 SVG 图像哦，可以参考 `dist/banner.svg` 和 `template/banner.svg` 进行修改

脚本部分是为了同步头像到对象存储，同时把新的头像嵌入到 `template/banner.svg` 里面，不需要同步头像的话可以直接手工修改 SVG _(:3」 ∠)_

**Comment by zhousiru** [comment]
具体的话，需要修改文字部分，把文字转为路径替换掉以下几行：

https://github.com/Zhousiru/Zhousiru/blob/f792930d02d903815655b2cbfdcd8a572c6089b1/dist/banner.svg#L33-L36

头像部分，把图像转为 base64，替换掉原来的 `href`

https://github.com/Zhousiru/Zhousiru/blob/f792930d02d903815655b2cbfdcd8a572c6089b1/dist/banner.svg#L42
