### ISSUE TITLE
具体的话，需要修改文字部分，把文字转为路径替换掉以下几行：

### ISSUE THREAD

**Issue by TwinZagreus** [Zhousiru/Zhousiru#2]
具体的话，需要修改文字部分，把文字转为路径替换掉以下几行：

https://github.com/Zhousiru/Zhousiru/blob/f792930d02d903815655b2cbfdcd8a572c6089b1/dist/banner.svg#L33-L36

头像部分，把图像转为 base64，替换掉原来的 `href`

https://github.com/Zhousiru/Zhousiru/blob/f792930d02d903815655b2cbfdcd8a572c6089b1/dist/banner.svg#L42

_Originally posted by @Zhousiru in https://github.com/Zhousiru/Zhousiru/issues/1#issuecomment-1925821952_

**Comment by TwinZagreus** [comment]
好的，谢谢大佬。就是说实时更新还是有服务器的，就是你自己还维护一个后端接口是吧

**Comment by zhousiru** [comment]
同步头像的话是在 GitHub Actions 里运行的脚本，抓取最新的头像，然后上传到 minio 兼容的对象存储（腾讯云 COS 或者阿里云 OSS 之类的）_(:3」 ∠)_



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月5日(周一) 凌晨0:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zhousiru/Zhousiru] 具体的话，需要修改文字部分，把文字转为路径替换掉以下几行： (Issue #2)




 
好的，谢谢大佬。就是说实时更新还是有服务器的，就是你自己还维护一个后端接口是吧

**Comment by TwinZagreus** [comment]
大致了解了，谢谢大佬，祝大佬发量嘎嘎好
